name: snowflake_dbt
version: 1.0.0
config-version: 2

profile: snowflake_dbt

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
analysis-paths: ["analyses"]
test-paths: ["tests"]

clean-targets:
  - target
  - dbt_packages

models:
  snowflake_dbt:
    +database: BRONZE_DEV
    +materialized: table

    bronze:
      +database: BRONZE_DEV
      +schema: BRONZE

    silver:
      dimensions:
        +database: SILVER_DEV
        +schema: DIMENSIONS
      facts:
        +database: SILVER_DEV
        +schema: FACTS

    gold:
      dataset:
        +database: GOLDEN_DEV
        +schema: DATASET

seeds:
  snowflake_dbt:
    +database: BRONZE_DEV
    +schema: BRONZE
    +quote_columns: false
