-- Production bootstrap for Snowflake + dbt medallion architecture
-- Layer mapping in one database:
-- BRONZE (seed/raw) -> DIMENSIONS/FACTS (silver) -> DATASET (gold)

-- ------------------------------------------------------------------
-- 1) Create warehouses and core objects
-- ------------------------------------------------------------------
USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS WH_PROD_INGEST
  WAREHOUSE_SIZE = 'SMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE WAREHOUSE IF NOT EXISTS WH_PROD_DBT
  WAREHOUSE_SIZE = 'MEDIUM'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE WAREHOUSE IF NOT EXISTS WH_PROD_BI
  WAREHOUSE_SIZE = 'MEDIUM'
  AUTO_SUSPEND = 300
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS ANALYTICS_PROD;
CREATE SCHEMA IF NOT EXISTS ANALYTICS_PROD.BRONZE;
CREATE SCHEMA IF NOT EXISTS ANALYTICS_PROD.DIMENSIONS;
CREATE SCHEMA IF NOT EXISTS ANALYTICS_PROD.FACTS;
CREATE SCHEMA IF NOT EXISTS ANALYTICS_PROD.DATASET;
-- SECURITY schema keeps secrets isolated from data layers (BRONZE/SILVER/GOLD)
-- so access can be tightly scoped (for example, READ/USAGE on specific secrets only).
CREATE SCHEMA IF NOT EXISTS ANALYTICS_PROD.SECURITY;
-- INTEGRATION schema is dedicated to integration objects (for example GIT REPOSITORY)
-- to avoid mixing operational objects with data layer schemas.
CREATE SCHEMA IF NOT EXISTS ANALYTICS_PROD.INTEGRATION;

-- ------------------------------------------------------------------
-- 2) Create roles and service users
-- ------------------------------------------------------------------
USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS ROLE_PROD_INGEST;
CREATE ROLE IF NOT EXISTS ROLE_PROD_DBT;
CREATE ROLE IF NOT EXISTS ROLE_PROD_BI;

-- Replace temporary passwords with your secret-management flow.
CREATE USER IF NOT EXISTS SVC_INGEST
  PASSWORD = 'ChangeMe_Ingest_123!'
  DEFAULT_ROLE = ROLE_PROD_INGEST
  MUST_CHANGE_PASSWORD = TRUE;

CREATE USER IF NOT EXISTS SVC_DBT
  PASSWORD = 'ChangeMe_Dbt_123!'
  DEFAULT_ROLE = ROLE_PROD_DBT
  MUST_CHANGE_PASSWORD = TRUE;

GRANT ROLE ROLE_PROD_INGEST TO USER SVC_INGEST;
GRANT ROLE ROLE_PROD_DBT TO USER SVC_DBT;

-- ------------------------------------------------------------------
-- 3) Warehouse grants
-- ------------------------------------------------------------------
GRANT USAGE, OPERATE ON WAREHOUSE WH_PROD_INGEST TO ROLE ROLE_PROD_INGEST;
GRANT USAGE, OPERATE ON WAREHOUSE WH_PROD_DBT TO ROLE ROLE_PROD_DBT;
GRANT USAGE ON WAREHOUSE WH_PROD_BI TO ROLE ROLE_PROD_BI;

-- ------------------------------------------------------------------
-- 4) Database and schema grants
-- ------------------------------------------------------------------
GRANT USAGE ON DATABASE ANALYTICS_PROD TO ROLE ROLE_PROD_INGEST;
GRANT USAGE ON DATABASE ANALYTICS_PROD TO ROLE ROLE_PROD_DBT;
GRANT USAGE ON DATABASE ANALYTICS_PROD TO ROLE ROLE_PROD_BI;

-- Ingest: write only to BRONZE
GRANT USAGE ON SCHEMA ANALYTICS_PROD.BRONZE TO ROLE ROLE_PROD_INGEST;
GRANT CREATE TABLE, CREATE STAGE, CREATE FILE FORMAT ON SCHEMA ANALYTICS_PROD.BRONZE TO ROLE ROLE_PROD_INGEST;

-- dbt: seed/read BRONZE, write SILVER+GOLD
GRANT USAGE ON SCHEMA ANALYTICS_PROD.BRONZE TO ROLE ROLE_PROD_DBT;
GRANT CREATE TABLE ON SCHEMA ANALYTICS_PROD.BRONZE TO ROLE ROLE_PROD_DBT;
GRANT SELECT ON ALL TABLES IN SCHEMA ANALYTICS_PROD.BRONZE TO ROLE ROLE_PROD_DBT;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ANALYTICS_PROD.BRONZE TO ROLE ROLE_PROD_DBT;

GRANT USAGE ON SCHEMA ANALYTICS_PROD.DIMENSIONS TO ROLE ROLE_PROD_DBT;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA ANALYTICS_PROD.DIMENSIONS TO ROLE ROLE_PROD_DBT;
GRANT USAGE ON SCHEMA ANALYTICS_PROD.FACTS TO ROLE ROLE_PROD_DBT;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA ANALYTICS_PROD.FACTS TO ROLE ROLE_PROD_DBT;
GRANT USAGE ON SCHEMA ANALYTICS_PROD.DATASET TO ROLE ROLE_PROD_DBT;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA ANALYTICS_PROD.DATASET TO ROLE ROLE_PROD_DBT;

-- Dedicated schemas for secrets/integrations used by automation.
GRANT USAGE ON SCHEMA ANALYTICS_PROD.SECURITY TO ROLE ROLE_PROD_DBT;
GRANT USAGE ON SCHEMA ANALYTICS_PROD.INTEGRATION TO ROLE ROLE_PROD_DBT;
GRANT CREATE GIT REPOSITORY ON SCHEMA ANALYTICS_PROD.INTEGRATION TO ROLE ROLE_PROD_DBT;

-- BI: read only from DATASET
GRANT USAGE ON SCHEMA ANALYTICS_PROD.DATASET TO ROLE ROLE_PROD_BI;
GRANT SELECT ON ALL TABLES IN SCHEMA ANALYTICS_PROD.DATASET TO ROLE ROLE_PROD_BI;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ANALYTICS_PROD.DATASET TO ROLE ROLE_PROD_BI;
GRANT SELECT ON ALL VIEWS IN SCHEMA ANALYTICS_PROD.DATASET TO ROLE ROLE_PROD_BI;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA ANALYTICS_PROD.DATASET TO ROLE ROLE_PROD_BI;

-- Optional: grant ROLE_PROD_BI to your BI users/groups separately.

-- ------------------------------------------------------------------
-- 5) Future object ownership pattern for dbt-created objects
-- ------------------------------------------------------------------
USE ROLE ACCOUNTADMIN;
GRANT OWNERSHIP ON ALL TABLES IN SCHEMA ANALYTICS_PROD.DIMENSIONS TO ROLE ROLE_PROD_DBT COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ALL TABLES IN SCHEMA ANALYTICS_PROD.FACTS TO ROLE ROLE_PROD_DBT COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ALL TABLES IN SCHEMA ANALYTICS_PROD.DATASET TO ROLE ROLE_PROD_DBT COPY CURRENT GRANTS;
