-- Minimal bootstrap for Snowflake + dbt medallion architecture (DEV databases)
-- Layer mapping across databases:
-- BRONZE_DEV.BRONZE -> SILVER_DEV.{DIMENSIONS,FACTS} -> GOLDEN_DEV.DATASET

-- ------------------------------------------------------------------
-- 1) Core infrastructure (ACCOUNTADMIN)
-- ------------------------------------------------------------------
USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS WH_DEV_INGEST
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE WAREHOUSE IF NOT EXISTS WH_DEV_DBT
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE WAREHOUSE IF NOT EXISTS WH_DEV_BI
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS BRONZE_DEV;
CREATE DATABASE IF NOT EXISTS SILVER_DEV;
CREATE DATABASE IF NOT EXISTS GOLDEN_DEV;
CREATE DATABASE IF NOT EXISTS PLATFORM_DEV;

CREATE SCHEMA IF NOT EXISTS BRONZE_DEV.BRONZE;
CREATE SCHEMA IF NOT EXISTS SILVER_DEV.DIMENSIONS;
CREATE SCHEMA IF NOT EXISTS SILVER_DEV.FACTS;
CREATE SCHEMA IF NOT EXISTS GOLDEN_DEV.DATASET;

-- Operational schemas used by Git integration and secrets.
CREATE SCHEMA IF NOT EXISTS PLATFORM_DEV.SECURITY;
CREATE SCHEMA IF NOT EXISTS PLATFORM_DEV.INTEGRATION;

-- ------------------------------------------------------------------
-- 2) Roles and users (SECURITYADMIN)
-- ------------------------------------------------------------------
USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS ROLE_DEV_INGEST;
CREATE ROLE IF NOT EXISTS ROLE_DEV_DBT;
CREATE ROLE IF NOT EXISTS ROLE_DEV_BI;

-- Optional service/interface users. Replace temporary passwords.
CREATE USER IF NOT EXISTS SVC_DEV_INGEST
  PASSWORD = 'ChangeMe_Ingest_123!'
  DEFAULT_ROLE = ROLE_DEV_INGEST
  DEFAULT_WAREHOUSE = WH_DEV_INGEST
  MUST_CHANGE_PASSWORD = TRUE;

CREATE USER IF NOT EXISTS EXT_DEV_DBT
  PASSWORD = 'ChangeMe_ExtDbt_123!'
  DEFAULT_ROLE = ROLE_DEV_DBT
  DEFAULT_WAREHOUSE = WH_DEV_DBT
  MUST_CHANGE_PASSWORD = TRUE;

CREATE USER IF NOT EXISTS EXT_DEV_BI
  PASSWORD = 'ChangeMe_ExtBi_123!'
  DEFAULT_ROLE = ROLE_DEV_BI
  DEFAULT_WAREHOUSE = WH_DEV_BI
  MUST_CHANGE_PASSWORD = TRUE;

GRANT ROLE ROLE_DEV_INGEST TO USER SVC_DEV_INGEST;
GRANT ROLE ROLE_DEV_DBT TO USER EXT_DEV_DBT;
GRANT ROLE ROLE_DEV_BI TO USER EXT_DEV_BI;

-- ------------------------------------------------------------------
-- 3) Warehouse grants
-- ------------------------------------------------------------------
GRANT USAGE, OPERATE ON WAREHOUSE WH_DEV_INGEST TO ROLE ROLE_DEV_INGEST;
GRANT USAGE, OPERATE ON WAREHOUSE WH_DEV_DBT TO ROLE ROLE_DEV_DBT;
GRANT USAGE ON WAREHOUSE WH_DEV_BI TO ROLE ROLE_DEV_BI;

-- ------------------------------------------------------------------
-- 4) Database-level grants
-- ------------------------------------------------------------------
-- Ingest
GRANT USAGE ON DATABASE BRONZE_DEV TO ROLE ROLE_DEV_INGEST;

-- dbt
GRANT USAGE ON DATABASE BRONZE_DEV TO ROLE ROLE_DEV_DBT;
GRANT USAGE ON DATABASE SILVER_DEV TO ROLE ROLE_DEV_DBT;
GRANT USAGE ON DATABASE GOLDEN_DEV TO ROLE ROLE_DEV_DBT;
GRANT USAGE ON DATABASE PLATFORM_DEV TO ROLE ROLE_DEV_DBT;

-- dbt may issue CREATE SCHEMA IF NOT EXISTS during runs.
GRANT CREATE SCHEMA ON DATABASE BRONZE_DEV TO ROLE ROLE_DEV_DBT;
GRANT CREATE SCHEMA ON DATABASE SILVER_DEV TO ROLE ROLE_DEV_DBT;
GRANT CREATE SCHEMA ON DATABASE GOLDEN_DEV TO ROLE ROLE_DEV_DBT;

-- BI
GRANT USAGE ON DATABASE SILVER_DEV TO ROLE ROLE_DEV_BI;
GRANT USAGE ON DATABASE GOLDEN_DEV TO ROLE ROLE_DEV_BI;

-- ------------------------------------------------------------------
-- 5) Schema/object grants by access pattern
-- ------------------------------------------------------------------

-- 5a) BRONZE access
-- Ingest: read/write ingestion area.
GRANT USAGE ON SCHEMA BRONZE_DEV.BRONZE TO ROLE ROLE_DEV_INGEST;
GRANT CREATE TABLE, CREATE STAGE, CREATE FILE FORMAT ON SCHEMA BRONZE_DEV.BRONZE TO ROLE ROLE_DEV_INGEST;
GRANT SELECT ON ALL TABLES IN SCHEMA BRONZE_DEV.BRONZE TO ROLE ROLE_DEV_INGEST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA BRONZE_DEV.BRONZE TO ROLE ROLE_DEV_INGEST;

-- dbt: seed/read BRONZE.
GRANT USAGE ON SCHEMA BRONZE_DEV.BRONZE TO ROLE ROLE_DEV_DBT;
GRANT CREATE TABLE ON SCHEMA BRONZE_DEV.BRONZE TO ROLE ROLE_DEV_DBT;
GRANT SELECT ON ALL TABLES IN SCHEMA BRONZE_DEV.BRONZE TO ROLE ROLE_DEV_DBT;
GRANT SELECT ON FUTURE TABLES IN SCHEMA BRONZE_DEV.BRONZE TO ROLE ROLE_DEV_DBT;

-- 5b) SILVER + GOLD write access for dbt
GRANT USAGE ON SCHEMA SILVER_DEV.DIMENSIONS TO ROLE ROLE_DEV_DBT;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA SILVER_DEV.DIMENSIONS TO ROLE ROLE_DEV_DBT;

GRANT USAGE ON SCHEMA SILVER_DEV.FACTS TO ROLE ROLE_DEV_DBT;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA SILVER_DEV.FACTS TO ROLE ROLE_DEV_DBT;

GRANT USAGE ON SCHEMA GOLDEN_DEV.DATASET TO ROLE ROLE_DEV_DBT;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA GOLDEN_DEV.DATASET TO ROLE ROLE_DEV_DBT;

-- 5c) SILVER read access for BI
GRANT USAGE ON SCHEMA SILVER_DEV.DIMENSIONS TO ROLE ROLE_DEV_BI;
GRANT SELECT ON ALL TABLES IN SCHEMA SILVER_DEV.DIMENSIONS TO ROLE ROLE_DEV_BI;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SILVER_DEV.DIMENSIONS TO ROLE ROLE_DEV_BI;
GRANT SELECT ON ALL VIEWS IN SCHEMA SILVER_DEV.DIMENSIONS TO ROLE ROLE_DEV_BI;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA SILVER_DEV.DIMENSIONS TO ROLE ROLE_DEV_BI;

GRANT USAGE ON SCHEMA SILVER_DEV.FACTS TO ROLE ROLE_DEV_BI;
GRANT SELECT ON ALL TABLES IN SCHEMA SILVER_DEV.FACTS TO ROLE ROLE_DEV_BI;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SILVER_DEV.FACTS TO ROLE ROLE_DEV_BI;
GRANT SELECT ON ALL VIEWS IN SCHEMA SILVER_DEV.FACTS TO ROLE ROLE_DEV_BI;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA SILVER_DEV.FACTS TO ROLE ROLE_DEV_BI;

-- 5d) GOLD read access for BI
GRANT USAGE ON SCHEMA GOLDEN_DEV.DATASET TO ROLE ROLE_DEV_BI;
GRANT SELECT ON ALL TABLES IN SCHEMA GOLDEN_DEV.DATASET TO ROLE ROLE_DEV_BI;
GRANT SELECT ON FUTURE TABLES IN SCHEMA GOLDEN_DEV.DATASET TO ROLE ROLE_DEV_BI;
GRANT SELECT ON ALL VIEWS IN SCHEMA GOLDEN_DEV.DATASET TO ROLE ROLE_DEV_BI;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA GOLDEN_DEV.DATASET TO ROLE ROLE_DEV_BI;

-- 5e) Operational schemas for dbt automation / Git integration
GRANT USAGE ON SCHEMA PLATFORM_DEV.SECURITY TO ROLE ROLE_DEV_DBT;
GRANT USAGE ON SCHEMA PLATFORM_DEV.INTEGRATION TO ROLE ROLE_DEV_DBT;

-- ------------------------------------------------------------------
-- 6) Ownership pattern for dbt-managed tables (ACCOUNTADMIN)
-- ------------------------------------------------------------------
USE ROLE ACCOUNTADMIN;

GRANT OWNERSHIP ON ALL TABLES IN SCHEMA SILVER_DEV.DIMENSIONS TO ROLE ROLE_DEV_DBT COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ALL TABLES IN SCHEMA SILVER_DEV.FACTS TO ROLE ROLE_DEV_DBT COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ALL TABLES IN SCHEMA GOLDEN_DEV.DATASET TO ROLE ROLE_DEV_DBT COPY CURRENT GRANTS;
