-- Production bootstrap for Snowflake + dbt medallion architecture
-- Layer mapping in one database:
-- BRONZE (seed/raw) -> DIMENSIONS/FACTS (silver) -> DATASET (gold)

-- ------------------------------------------------------------------
-- 1) Core infrastructure (ACCOUNTADMIN)
-- ------------------------------------------------------------------
USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS WH_PROD_INGEST
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE WAREHOUSE IF NOT EXISTS WH_PROD_DBT
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE WAREHOUSE IF NOT EXISTS WH_PROD_BI
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS ANALYTICS_PROD;
CREATE SCHEMA IF NOT EXISTS ANALYTICS_PROD.BRONZE;
CREATE SCHEMA IF NOT EXISTS ANALYTICS_PROD.DIMENSIONS;
CREATE SCHEMA IF NOT EXISTS ANALYTICS_PROD.FACTS;
CREATE SCHEMA IF NOT EXISTS ANALYTICS_PROD.DATASET;
CREATE SCHEMA IF NOT EXISTS ANALYTICS_PROD.SECURITY;
CREATE SCHEMA IF NOT EXISTS ANALYTICS_PROD.INTEGRATION;

-- ------------------------------------------------------------------
-- 2) Roles and users (SECURITYADMIN)
-- ------------------------------------------------------------------
USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS ROLE_PROD_INGEST;
CREATE ROLE IF NOT EXISTS ROLE_PROD_DBT;
CREATE ROLE IF NOT EXISTS ROLE_PROD_BI;
CREATE ROLE IF NOT EXISTS ROLE_PROD_BI_ANALYST;

-- Optional service/interface users. Replace temporary passwords.
CREATE USER IF NOT EXISTS SVC_INGEST
  PASSWORD = 'ChangeMe_Ingest_123!'
  DEFAULT_ROLE = ROLE_PROD_INGEST
  DEFAULT_WAREHOUSE = WH_PROD_INGEST
  MUST_CHANGE_PASSWORD = TRUE;

CREATE USER IF NOT EXISTS EXT_BI
  PASSWORD = 'ChangeMe_ExtBi_123!'
  DEFAULT_ROLE = ROLE_PROD_BI
  DEFAULT_WAREHOUSE = WH_PROD_BI
  MUST_CHANGE_PASSWORD = TRUE;

CREATE USER IF NOT EXISTS EXT_BI_ANALYST
  PASSWORD = 'ChangeMe_ExtBiAnalyst_123!'
  DEFAULT_ROLE = ROLE_PROD_BI_ANALYST
  DEFAULT_WAREHOUSE = WH_PROD_BI
  MUST_CHANGE_PASSWORD = TRUE;

CREATE USER IF NOT EXISTS EXT_DBT
  PASSWORD = 'ChangeMe_ExtDbt_123!'
  DEFAULT_ROLE = ROLE_PROD_DBT
  DEFAULT_WAREHOUSE = WH_PROD_DBT
  MUST_CHANGE_PASSWORD = TRUE;

GRANT ROLE ROLE_PROD_INGEST TO USER SVC_INGEST;
GRANT ROLE ROLE_PROD_BI TO USER EXT_BI;
GRANT ROLE ROLE_PROD_BI_ANALYST TO USER EXT_BI_ANALYST;
GRANT ROLE ROLE_PROD_DBT TO USER EXT_DBT;

-- BI analyst inherits BI gold read access, then adds BRONZE read.
GRANT ROLE ROLE_PROD_BI TO ROLE ROLE_PROD_BI_ANALYST;

-- ------------------------------------------------------------------
-- 3) Warehouse grants
-- ------------------------------------------------------------------
GRANT USAGE, OPERATE ON WAREHOUSE WH_PROD_INGEST TO ROLE ROLE_PROD_INGEST;
GRANT USAGE, OPERATE ON WAREHOUSE WH_PROD_DBT TO ROLE ROLE_PROD_DBT;
GRANT USAGE ON WAREHOUSE WH_PROD_BI TO ROLE ROLE_PROD_BI;
GRANT USAGE ON WAREHOUSE WH_PROD_BI TO ROLE ROLE_PROD_BI_ANALYST;

-- ------------------------------------------------------------------
-- 4) Database-level grants
-- ------------------------------------------------------------------
GRANT USAGE ON DATABASE ANALYTICS_PROD TO ROLE ROLE_PROD_INGEST;
GRANT USAGE ON DATABASE ANALYTICS_PROD TO ROLE ROLE_PROD_DBT;
GRANT USAGE ON DATABASE ANALYTICS_PROD TO ROLE ROLE_PROD_BI;
GRANT USAGE ON DATABASE ANALYTICS_PROD TO ROLE ROLE_PROD_BI_ANALYST;

-- dbt may issue CREATE SCHEMA IF NOT EXISTS during runs.
GRANT CREATE SCHEMA ON DATABASE ANALYTICS_PROD TO ROLE ROLE_PROD_DBT;

-- ------------------------------------------------------------------
-- 5) Schema/object grants by access pattern
-- ------------------------------------------------------------------

-- 5a) BRONZE access
-- Ingest: write-only ingestion area.
GRANT USAGE ON SCHEMA ANALYTICS_PROD.BRONZE TO ROLE ROLE_PROD_INGEST;
GRANT CREATE TABLE, CREATE STAGE, CREATE FILE FORMAT ON SCHEMA ANALYTICS_PROD.BRONZE TO ROLE ROLE_PROD_INGEST;

-- dbt: seed/read BRONZE.
GRANT USAGE ON SCHEMA ANALYTICS_PROD.BRONZE TO ROLE ROLE_PROD_DBT;
GRANT CREATE TABLE ON SCHEMA ANALYTICS_PROD.BRONZE TO ROLE ROLE_PROD_DBT;
GRANT SELECT ON ALL TABLES IN SCHEMA ANALYTICS_PROD.BRONZE TO ROLE ROLE_PROD_DBT;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ANALYTICS_PROD.BRONZE TO ROLE ROLE_PROD_DBT;

-- BI Analyst: read BRONZE.
GRANT USAGE ON SCHEMA ANALYTICS_PROD.BRONZE TO ROLE ROLE_PROD_BI_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA ANALYTICS_PROD.BRONZE TO ROLE ROLE_PROD_BI_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ANALYTICS_PROD.BRONZE TO ROLE ROLE_PROD_BI_ANALYST;

-- 5b) SILVER + GOLD write access for dbt
GRANT USAGE ON SCHEMA ANALYTICS_PROD.DIMENSIONS TO ROLE ROLE_PROD_DBT;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA ANALYTICS_PROD.DIMENSIONS TO ROLE ROLE_PROD_DBT;

GRANT USAGE ON SCHEMA ANALYTICS_PROD.FACTS TO ROLE ROLE_PROD_DBT;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA ANALYTICS_PROD.FACTS TO ROLE ROLE_PROD_DBT;

GRANT USAGE ON SCHEMA ANALYTICS_PROD.DATASET TO ROLE ROLE_PROD_DBT;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA ANALYTICS_PROD.DATASET TO ROLE ROLE_PROD_DBT;

-- 5c) GOLD read access for BI
GRANT USAGE ON SCHEMA ANALYTICS_PROD.DATASET TO ROLE ROLE_PROD_BI;
GRANT SELECT ON ALL TABLES IN SCHEMA ANALYTICS_PROD.DATASET TO ROLE ROLE_PROD_BI;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ANALYTICS_PROD.DATASET TO ROLE ROLE_PROD_BI;
GRANT SELECT ON ALL VIEWS IN SCHEMA ANALYTICS_PROD.DATASET TO ROLE ROLE_PROD_BI;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA ANALYTICS_PROD.DATASET TO ROLE ROLE_PROD_BI;

-- 5d) Operational schemas for dbt automation
GRANT USAGE ON SCHEMA ANALYTICS_PROD.SECURITY TO ROLE ROLE_PROD_DBT;
GRANT USAGE ON SCHEMA ANALYTICS_PROD.INTEGRATION TO ROLE ROLE_PROD_DBT;

-- Optional: grant ROLE_PROD_BI / ROLE_PROD_BI_ANALYST to BI users/groups.

-- ------------------------------------------------------------------
-- 6) Ownership pattern for dbt-managed tables (ACCOUNTADMIN)
-- ------------------------------------------------------------------
USE ROLE ACCOUNTADMIN;

GRANT OWNERSHIP ON ALL TABLES IN SCHEMA ANALYTICS_PROD.DIMENSIONS TO ROLE ROLE_PROD_DBT COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ALL TABLES IN SCHEMA ANALYTICS_PROD.FACTS TO ROLE ROLE_PROD_DBT COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ALL TABLES IN SCHEMA ANALYTICS_PROD.DATASET TO ROLE ROLE_PROD_DBT COPY CURRENT GRANTS;
