-- Minimal Snowflake Git integration bootstrap for this dbt project
--
-- Replace <YOUR_GITHUB_CLASSIC_PAT> before running.
-- This script can run before or after sql/bootstrap_dev.sql.

-- ------------------------------------------------------------------
-- 1) Integration + containers (ACCOUNTADMIN)
-- ------------------------------------------------------------------
USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS PLATFORM_DEV;
CREATE SCHEMA IF NOT EXISTS PLATFORM_DEV.SECURITY;
CREATE SCHEMA IF NOT EXISTS PLATFORM_DEV.INTEGRATION;

CREATE OR REPLACE API INTEGRATION GITHUB_INT_SNOWFLAKE_DBT
  API_PROVIDER = git_https_api
  API_ALLOWED_PREFIXES = (
    'https://github.com/mareksyldatk/snowflake-dbt.git'
  )
  ALLOWED_AUTHENTICATION_SECRETS = ALL
  ENABLED = TRUE;

GRANT USAGE ON INTEGRATION GITHUB_INT_SNOWFLAKE_DBT TO ROLE SECURITYADMIN;
GRANT USAGE ON DATABASE PLATFORM_DEV TO ROLE SECURITYADMIN;
GRANT USAGE ON SCHEMA PLATFORM_DEV.SECURITY TO ROLE SECURITYADMIN;
GRANT CREATE SECRET ON SCHEMA PLATFORM_DEV.SECURITY TO ROLE SECURITYADMIN;

-- ------------------------------------------------------------------
-- 2) Secret creation (SECURITYADMIN)
-- ------------------------------------------------------------------
USE ROLE SECURITYADMIN;
USE DATABASE PLATFORM_DEV;
USE SCHEMA SECURITY;

CREATE ROLE IF NOT EXISTS ROLE_DEV_DBT;

CREATE OR REPLACE SECRET GITHUB_PAT_SECRET
  TYPE = PASSWORD
  USERNAME = 'mareksyldatk'
  PASSWORD = '<YOUR_GITHUB_CLASSIC_PAT>';

-- ------------------------------------------------------------------
-- 3) Grants for dbt runtime role
-- ------------------------------------------------------------------
GRANT USAGE ON INTEGRATION GITHUB_INT_SNOWFLAKE_DBT TO ROLE ROLE_DEV_DBT;
GRANT USAGE ON DATABASE PLATFORM_DEV TO ROLE ROLE_DEV_DBT;
GRANT USAGE ON SCHEMA PLATFORM_DEV.SECURITY TO ROLE ROLE_DEV_DBT;
GRANT USAGE ON SCHEMA PLATFORM_DEV.INTEGRATION TO ROLE ROLE_DEV_DBT;
GRANT READ ON SECRET PLATFORM_DEV.SECURITY.GITHUB_PAT_SECRET TO ROLE ROLE_DEV_DBT;
GRANT USAGE ON SECRET PLATFORM_DEV.SECURITY.GITHUB_PAT_SECRET TO ROLE ROLE_DEV_DBT;
